# Generated by Django 4.2.11 on 2024-03-23 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image_alter_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 23, 7, 40, 4, 336579, tzinfo=datetime.timezone.utc)),
        ),
    ]
