# Generated by Django 4.2.11 on 2024-03-23 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 23, 8, 10, 1, 420008, tzinfo=datetime.timezone.utc)),
        ),
    ]
