# Generated by Django 4.2.11 on 2024-03-23 09:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 23, 9, 27, 11, 843333, tzinfo=datetime.timezone.utc)),
        ),
    ]
