# Generated by Django 4.2.11 on 2024-03-23 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='django-rest-framework.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 23, 7, 39, 28, 798650, tzinfo=datetime.timezone.utc)),
        ),
    ]
