# Generated by Django 4.2.11 on 2024-03-23 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='no-image.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 23, 7, 42, 16, 638411, tzinfo=datetime.timezone.utc)),
        ),
    ]
